actions:
  abortActions: []
  emailNotifications: []
  setVariableActions:
  - description: null
    exitCodes: null
    notificationOption: Operation Failure
    notifyOnEarlyFinish: false
    notifyOnLateFinish: false
    notifyOnLateStart: true
    notifyOnProjectedLate: false
    status: null
    sysId: c800ccf1f0fb4be7b5bf78bb9c2f58ed
    variableName: middle_stop_recurrence_counter
    variableScope: Global
    variableValue: '0'
  snmpNotifications: []
  systemOperations:
  - agent: null
    agentCluster: null
    agentClusterVar: null
    agentVar: null
    description: null
    execCommand: Force Finish/Cancel (Halt)
    execCriteria: Oldest Active Instance
    execId: ${ops_top_level_workflow_id}
    execLookupOption: Instance Id
    execName: null
    execWorkflowName: null
    execWorkflowNameCond: Equals
    exitCodes: null
    limit: null
    notificationOption: Operation Failure
    notifyOnEarlyFinish: false
    notifyOnLateFinish: false
    notifyOnLateStart: true
    notifyOnProjectedLate: false
    operation: Run Task Instance Command
    overrideTriggerDateOffset: null
    overrideTriggerDateTime: false
    overrideTriggerTime: 00:00
    status: null
    sysId: f9efbe9fdf684ae4908686e3d36dbbe9
    task: null
    taskLimitType: Unlimited
    taskVar: null
    trigger: null
    triggerVar: null
    variables: []
    variablesUnresolved: false
    virtualResource: null
    virtualResourceVar: null
agent: 129.213.52.12-rehl79- AGNT0001
agentCluster: null
agentClusterVar: null
agentVar: null
broadcastCluster: null
broadcastClusterVar: null
command: ./Pre_stopMW.sh
commandOrScript: Command
cpDuration: null
cpDurationUnit: Minutes
credentials: null
credentialsVar: null
customField1:
  label: null
  value: null
customField2:
  label: null
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
environment: []
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exitCodeOutput: null
exitCodeProcessing: Success Exitcode Range
exitCodeText: null
exitCodes: '0'
exportReleaseLevel: 7.4.0.0
exportTable: ops_task_unix
firstRun: ''
holdResources: false
lastRun: ''
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:01:10
lsEnabled: true
lsNthAmount: 5
lsTime: 00:00
lsType: Duration
name: Pre_stopMW - stop Middleware java
notes: []
opswiseGroups: []
outputFailureOnly: false
outputReturnFile: null
outputReturnNline: '100'
outputReturnSline: '1'
outputReturnText: null
outputReturnType: OUTERR
outputType: STDOUT
parameters: null
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
retryExitCodes: null
retryIndefinitely: false
retryInterval: 60
retryMaximum: 0
retrySuppressFailure: false
runAsSudo: false
runCount: 0
runTime: 0
runtimeDir: /home/vpsadmin/VPBS.Middle
script: null
simulation: false
startHeld: false
startHeldReason: null
summary: null
sysId: eeade3cc4b214603bb6630dc427ba9a0
timeZonePref: -- System Default --
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskUnix
userEstimatedDuration: null
variables: []
version: 2
virtualResources: []
waitForOutput: true
