actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
calculateCp: false
calendar: null
cpDuration: null
cpDurationUnit: Minutes
criticalEndpoints: []
customField1:
  label: null
  value: null
customField2:
  label: null
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exportReleaseLevel: 7.4.0.0
exportTable: ops_task_workflow
firstRun: ''
holdResources: false
lastRun: ''
layoutOption: -- None --
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
name: Middleware Stop Workflow
notes: []
numberOfTasks: 5
opswiseGroups: []
overrideCalendar: false
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
runCount: 0
runCriteria:
- businessDay: false
  complex: false
  complexAdjective: Every
  complexAdjustment: None
  complexAdjustmentAmount: 1
  complexAdjustmentType: Day
  complexNoun:
    value: Day
  complexNouns:
  - value: Day
  complexNthAmount: 5
  complexQualifier:
    value: Year
  complexQualifiers:
  - value: Year
  customDay: false
  customDayChoice: null
  description: null
  evaluateAt: Run Time
  holiday: false
  holidayAdjustment: None
  holidayAdjustmentAmount: 1
  holidayAdjustmentType: Day
  specificDay: false
  specificDayFri: false
  specificDayMon: false
  specificDaySat: false
  specificDaySun: false
  specificDayThu: false
  specificDayTue: false
  specificDayWed: false
  sysId: 95377fc7a564412c8886bb60d00ec46f
  task: Sleep 1 min after each retry
  type: Skip Criteria
  variable: true
  variableName: middle_stop_recurrence_counter
  variableOp: '='
  variableValue: '0'
  vertexId: Any
runTime: 0
simulation: false
skippedOption: Show Skipped
startHeld: false
startHeldReason: null
stepActions: []
stepConditions: []
summary: null
sysId: edae0b64c53949bf99326d076d3d9e3c
timeZonePref: -- System Default --
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskWorkflow
userEstimatedDuration: null
variables: []
version: 1
virtualResources: []
workflowEdges:
- condition:
    value: Success/Failure
  sourceId:
    taskName: Pre_stopMW - stop Middleware java
    value: '2'
  straightEdge: true
  targetId:
    taskName: Hold 20 seconds
    value: '25'
- condition:
    value: Success
  sourceId:
    taskName: Hold 20 seconds
    value: '25'
  straightEdge: true
  targetId:
    taskName: check middle_stop java process not exist
    value: '10'
- condition:
    firstValue: ${middle_stop_recurrence_counter}
    operator: <
    secondValue: '3'
    type: Variable
  sourceId:
    taskName: Sleep 1 min after each retry
    value: '51'
  straightEdge: true
  targetId:
    taskName: Pre_stopMW - stop Middleware java
    value: '2'
- condition:
    value: Success
  sourceId:
    taskName: check middle_stop java process not exist
    value: '10'
  straightEdge: true
  targetId:
    taskName: SyncMaster Start Workflow
    value: '53'
workflowVertices:
- alias: null
  task:
    value: Pre_stopMW - stop Middleware java
  vertexId: '2'
  vertexX: '200'
  vertexY: '190'
- alias: null
  task:
    value: check middle_stop java process not exist
  vertexId: '10'
  vertexX: '600'
  vertexY: '190'
- alias: null
  task:
    value: Hold 20 seconds
  vertexId: '25'
  vertexX: '390'
  vertexY: '190'
- alias: null
  task:
    value: Sleep 1 min after each retry
  vertexId: '51'
  vertexX: '-20'
  vertexY: '190'
- alias: null
  task:
    value: SyncMaster Start Workflow
  vertexId: '53'
  vertexX: '820'
  vertexY: '190'
